import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { SignOutButton } from "@/components/sign-out-button";
import { requireStaff } from "@/lib/auth/require-staff";
import { addCopy, addMember, addMembershipType, addTitle, assignStaffRole, issueLoan, returnLoan, updateCopyStatus, updateMemberStatus, updateTitleStatus } from "./actions";

export const metadata: Metadata = { title: "CBT Library administration" };
const copyStatuses = ["available", "on_loan", "reserved", "lost", "missing", "damaged", "under_repair", "reference_only", "withdrawn"] as const;
const titleStatuses = ["draft", "review", "published", "archived"] as const;
const readable = (value: string) => value.replaceAll("_", " ");
function related<T>(value: T | T[] | null | undefined): T | null { return Array.isArray(value) ? value[0] ?? null : value ?? null; }

export default async function AdminPage() {
  const auth = await requireStaff(["admin"]);
  if (!auth.ok) redirect("/login?reason=admin");
  const now = new Date().toISOString();
  const [titleCount, copyCount, memberCount, loanCount, overdueCount, titles, copies, members, types, shelves, loans, staff] = await Promise.all([
    auth.supabase.from("bibliographic_records").select("id", { count: "exact", head: true }),
    auth.supabase.from("physical_copies").select("id", { count: "exact", head: true }),
    auth.supabase.from("members").select("id", { count: "exact", head: true }),
    auth.supabase.from("loans").select("id", { count: "exact", head: true }).in("status", ["active", "overdue"]),
    auth.supabase.from("loans").select("id", { count: "exact", head: true }).in("status", ["active", "overdue"]).lt("current_due_at", now),
    auth.supabase.from("bibliographic_records").select("id,title,subtitle,isbn_13,publication_year,status,updated_at").order("updated_at", { ascending: false }).limit(100),
    auth.supabase.from("physical_copies").select("id,accession_number,circulation_status,verification_status,bibliographic_records(title),shelves(code,library_locations(name))").order("updated_at", { ascending: false }).limit(100),
    auth.supabase.from("members").select("id,membership_number,full_name,email,phone,status,auth_user_id,membership_types(name)").order("full_name").limit(100),
    auth.supabase.from("membership_types").select("id,name,max_active_loans,loan_period_days").eq("active", true).order("name"),
    auth.supabase.from("shelves").select("id,code,library_locations(name)").eq("active", true).order("code"),
    auth.supabase.from("loans").select("id,status,current_due_at,members(full_name,membership_number),physical_copies(accession_number,bibliographic_records(title))").order("checked_out_at", { ascending: false }).limit(100),
    auth.supabase.from("profiles").select("id,display_name,active,staff_roles(role)").order("display_name"),
  ]);
  const titleRows = titles.data ?? [];
  const copyRows = copies.data ?? [];
  const memberRows = members.data ?? [];
  const loanRows = loans.data ?? [];
  const availableCopies = copyRows.filter((copy) => copy.circulation_status === "available" && copy.verification_status === "shelf_verified");
  const activeMembers = memberRows.filter((member) => member.status === "active");

  return <main className="admin-shell">
    <aside className="admin-sidebar"><div><p className="admin-logo">CBT</p><span>Library control</span></div><nav aria-label="Admin sections"><a href="#overview">Overview</a><a href="#catalogue">Catalogue</a><a href="#copies">Copies</a><a href="#members">Members</a><a href="#loans">Loans</a><a href="#staff">Staff access</a></nav><div className="admin-sidebar-footer"><Link href="/librarian">Librarian view</Link><Link href="/">Public catalogue</Link><SignOutButton /></div></aside>
    <section className="admin-content">
      <header className="admin-command" id="overview"><div><p className="eyebrow"><span>Administration</span> Live database</p><h1>Library operations</h1><p>Manage the pilot catalogue, verified copies, circulation, members, and staff permissions.</p></div><span className="admin-role-badge">Admin</span></header>
      <section className="admin-metrics" aria-label="Library totals"><article><span>Titles</span><strong>{titleCount.count ?? 0}</strong><small>catalogue records</small></article><article><span>Copies</span><strong>{copyCount.count ?? 0}</strong><small>physical items</small></article><article><span>Members</span><strong>{memberCount.count ?? 0}</strong><small>registered users</small></article><article><span>On loan</span><strong>{loanCount.count ?? 0}</strong><small>{overdueCount.count ?? 0} overdue</small></article></section>

      <AdminSection number="01" title="Catalogue" description="Create title-level records. Copies are attached separately." id="catalogue">
        <form action={addTitle} className="admin-form admin-create-card"><h3>Add title</h3><label>Title<input name="title" required /></label><label>Subtitle<input name="subtitle" /></label><div className="form-row"><label>ISBN-13<input name="isbn13" inputMode="numeric" /></label><label>Year<input name="publicationYear" type="number" min="1000" max="2200" /></label></div><label>Publishing status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="review">Needs review</option><option value="published">Published</option></select></label><button>Save title</button></form>
        <TableCard title="Recent titles" count={titleRows.length}><table className="data-table"><thead><tr><th>Title</th><th>ISBN</th><th>Year</th><th>Status</th></tr></thead><tbody>{titleRows.map((title) => <tr key={title.id}><td><strong>{title.title}</strong><small>{title.subtitle || "No subtitle"}</small></td><td>{title.isbn_13 || "—"}</td><td>{title.publication_year || "—"}</td><td><form action={updateTitleStatus} className="inline-form"><input type="hidden" name="id" value={title.id} /><select name="status" defaultValue={title.status}>{titleStatuses.map((status) => <option key={status}>{status}</option>)}</select><button>Save</button></form></td></tr>)}</tbody></table></TableCard>
      </AdminSection>

      <AdminSection number="02" title="Physical copies" description="Track accession numbers, shelves, verification, and availability." id="copies">
        <form action={addCopy} className="admin-form admin-create-card"><h3>Add copy</h3><label>Book title<select name="bibliographicRecordId" required><option value="">Choose title</option>{titleRows.map((title) => <option key={title.id} value={title.id}>{title.title}</option>)}</select></label><div className="form-row"><label>Accession number<input name="accessionNumber" required /></label><label>Barcode<input name="barcode" /></label></div><label>Shelf<select name="shelfId"><option value="">Not assigned</option>{(shelves.data ?? []).map((shelf) => <option key={shelf.id} value={shelf.id}>{related(shelf.library_locations)?.name} / {shelf.code}</option>)}</select></label><div className="form-row"><label>Availability<select name="circulationStatus" defaultValue="available"><option value="available">Available</option><option value="reference_only">Reference only</option><option value="under_repair">Under repair</option><option value="missing">Missing</option></select></label><label>Verification<select name="verificationStatus" defaultValue="register_only"><option value="register_only">Register only</option><option value="needs_review">Needs review</option><option value="shelf_verified">Shelf verified now</option><option value="missing_during_verification">Not found</option></select></label></div><button>Add physical copy</button></form>
        <TableCard title="Copy inventory" count={copyRows.length}><table className="data-table"><thead><tr><th>Book / accession</th><th>Shelf</th><th>Verified</th><th>Availability</th></tr></thead><tbody>{copyRows.map((copy) => { const book = related(copy.bibliographic_records); const shelf = related(copy.shelves); return <tr key={copy.id}><td><strong>{book?.title || "Untitled"}</strong><small>{copy.accession_number}</small></td><td>{shelf ? `${related(shelf.library_locations)?.name} / ${shelf.code}` : "Unassigned"}</td><td><Status value={copy.verification_status} good={copy.verification_status === "shelf_verified"} /></td><td><form action={updateCopyStatus} className="inline-form"><input type="hidden" name="id" value={copy.id} /><select name="circulationStatus" defaultValue={copy.circulation_status}>{copyStatuses.map((status) => <option key={status} value={status}>{readable(status)}</option>)}</select><button>Save</button></form></td></tr>; })}</tbody></table></TableCard>
      </AdminSection>

      <AdminSection number="03" title="Members" description="Google accounts link automatically when the email matches exactly." id="members">
        <div className="admin-form-stack"><form action={addMember} className="admin-form admin-create-card"><h3>Add member</h3><div className="form-row"><label>Membership no.<input name="membershipNumber" required /></label><label>Full name<input name="fullName" required /></label></div><div className="form-row"><label>Google email<input name="email" type="email" /></label><label>Phone<input name="phone" /></label></div><label>Membership type<select name="membershipTypeId" required><option value="">Choose type</option>{(types.data ?? []).map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label><div className="form-row"><label>Starts<input name="membershipStart" type="date" required /></label><label>Expires<input name="membershipExpiry" type="date" required /></label></div><button>Add member</button></form><form action={addMembershipType} className="admin-form admin-create-card compact"><h3>Add membership type</h3><label>Name<input name="name" required /></label><div className="form-row"><label>Book limit<input name="maxActiveLoans" type="number" min="0" defaultValue="2" required /></label><label>Loan days<input name="loanPeriodDays" type="number" min="1" defaultValue="14" required /></label><label>Renewals<input name="renewalLimit" type="number" min="0" defaultValue="1" required /></label></div><button>Add type</button></form></div>
        <TableCard title="Users database" count={memberRows.length}><table className="data-table"><thead><tr><th>Member</th><th>Contact</th><th>Login</th><th>Status</th></tr></thead><tbody>{memberRows.map((member) => <tr key={member.id}><td><strong>{member.full_name}</strong><small>{member.membership_number} · {related(member.membership_types)?.name || "No type"}</small></td><td>{member.email || member.phone || "—"}</td><td><Status value={member.auth_user_id ? "Linked" : "Not linked"} good={Boolean(member.auth_user_id)} /></td><td><form action={updateMemberStatus} className="inline-form"><input type="hidden" name="id" value={member.id} /><select name="status" defaultValue={member.status}><option value="active">Active</option><option value="blocked">Blocked</option><option value="expired">Expired</option><option value="inactive">Inactive</option></select><button>Save</button></form></td></tr>)}</tbody></table></TableCard>
      </AdminSection>

      <AdminSection number="04" title="Loans" description="Only shelf-verified, available copies can be issued." id="loans">
        <form action={issueLoan} className="admin-form admin-create-card"><h3>Check out a book</h3><label>Copy<select name="copyId" required><option value="">Choose verified copy</option>{availableCopies.map((copy) => <option key={copy.id} value={copy.id}>{related(copy.bibliographic_records)?.title} · {copy.accession_number}</option>)}</select></label><label>Member<select name="memberId" required><option value="">Choose active member</option>{activeMembers.map((member) => <option key={member.id} value={member.id}>{member.full_name} · {member.membership_number}</option>)}</select></label><label>Note<textarea name="note" rows={3} /></label><button>Check out</button></form>
        <TableCard title="Loan history" count={loanRows.length}><table className="data-table"><thead><tr><th>Book</th><th>Member</th><th>Due</th><th>Status</th><th /></tr></thead><tbody>{loanRows.map((loan) => { const open = loan.status === "active" || loan.status === "overdue"; const overdue = open && loan.current_due_at < now; const copy = related(loan.physical_copies); const member = related(loan.members); return <tr key={loan.id}><td><strong>{related(copy?.bibliographic_records)?.title || "Untitled"}</strong><small>{copy?.accession_number}</small></td><td>{member?.full_name}<small>{member?.membership_number}</small></td><td>{new Date(loan.current_due_at).toLocaleDateString("en-IN")}</td><td><Status value={overdue ? "overdue" : loan.status} good={!open} danger={overdue} /></td><td>{open ? <form action={returnLoan}><input type="hidden" name="loanId" value={loan.id} /><button className="table-action">Return</button></form> : null}</td></tr>; })}</tbody></table></TableCard>
      </AdminSection>

      <AdminSection number="05" title="Staff access" description="The person must sign in once before you can assign a role." id="staff">
        <form action={assignStaffRole} className="admin-form admin-create-card"><h3>Assign staff role</h3><label>Google account email<input name="email" type="email" required /></label><label>Display name<input name="displayName" required /></label><label>Role<select name="role" defaultValue="librarian"><option value="librarian">Librarian</option><option value="senior_librarian">Senior librarian</option><option value="data_entry_operator">Data entry operator</option><option value="read_only_staff">Read-only staff</option><option value="admin">Administrator</option></select></label><button>Assign role</button></form>
        <div className="admin-table-card"><div className="table-title"><h3>Staff directory</h3><span>{staff.data?.length ?? 0} accounts</span></div><div className="staff-list">{(staff.data ?? []).map((person) => <article key={person.id}><div className="staff-avatar">{person.display_name.slice(0, 1).toUpperCase()}</div><div><strong>{person.display_name}</strong><small>{person.staff_roles?.map((item) => readable(item.role)).join(" · ") || "No role"}</small></div><Status value={person.active ? "Active" : "Disabled"} good={person.active} /></article>)}</div></div>
      </AdminSection>
    </section>
  </main>;
}

function AdminSection({ number, title, description, id, children }: { number: string; title: string; description: string; id: string; children: React.ReactNode }) { return <section className="admin-section" id={id}><div className="section-heading"><div><span>{number}</span><h2>{title}</h2></div><p>{description}</p></div><div className="admin-layout-two">{children}</div></section>; }
function TableCard({ title, count, children }: { title: string; count: number; children: React.ReactNode }) { return <div className="admin-table-card"><div className="table-title"><h3>{title}</h3><span>{count} shown</span></div><div className="data-table-wrap">{children}</div></div>; }
function Status({ value, good, danger = false }: { value: string; good: boolean; danger?: boolean }) { return <span className={`status-pill ${danger ? "danger" : good ? "good" : "warn"}`}>{readable(value)}</span>; }
